#!/bin/bash
#Kiosk Install Script Created by Jeremy Lawing 5-15-12

if [ "$(id -u)" != "0" ]; 
then
   echo -e "This script must be run as root.\nPlease run with sudo or login as root to run this script." 1>&2
   exit 1
fi


echo -e "Welcome to the Kiosk Installer."
echo "Would you like to install? [yes/no]: "
read response

if [ "$response" = "yes" ]
then
	
		
		echo -e "\n---------------Installing ssh---------------1/8"
		apt-get -y install ssh		
		echo -e "\n---------------Installing expect---------------2/8"
		apt-get -y install expect	
		echo -e "\n---------------Installing git---------------3/8"
		apt-get -y install git	
		echo -e "\n---------------Installing gtk---------------4/8"
		apt-get -y install libgtk-3-dev
		echo -e "\n---------------Installing gobject---------------5/8"
		apt-get -y install python-gobject-dev
		echo -e "\n---------------Installing webkit---------------6/8"
		apt-get -y install python-webkit-dev
		echo -e "\n---------------Installing openssl---------------7/8"
		apt-get -y install python-openssl

		echo -e "\n---------------Downloading kiosk---------------"
		cd /opt
		git clone "http://code.google.com/p/libkiosk/" kiosk

		echo -e "\n---------------Installing kiosk---------------8/8"		
		cd /opt/kiosk
		chmod 755 Install.sh
		./Install.sh

		echo -e "\n---------------Installation Completed Successfully!---------------"

		echo -e "\n-----The system needs to reboot for the changes to take effect.-----"
		echo "-----Reboot now? [yes/no]:-----"
		read reboot

		if [ "$reboot" == "yes" ]
		then
			echo -e "\n---------------Rebooting---------------"
			sudo /sbin/reboot
		else
			exit 0
		fi
	
	
else
	echo "Sorry $response is not an available option.  Exiting."
	exit 0
fi

